### PR TITLE
Bitmark CLI: Complete Edit

### PR DESCRIPTION
**Pull request by shannona**

### CODE REVIEW

**Comment by vienlt** [comment]
@hxw: Could you help to review this PR?

**Review by hxw — APPROVED** [review]
Not sure about the word **Toggle** I would normaly use **Option**.

Otherwise looks good

**Comment by vienlt** [comment]
> Not sure about the word **Toggle** I would normaly use **Option**.
> 
> Otherwise looks good

@shannona

**Comment by shannona** [comment]
I agree. I was striving for parallel structures when it wasn't necessarily helpful. I'll take care of it.

**Comment by vienlt** [comment]
@shannona, @hxw: If you are ok with the editing and solved the comment, we can merge the branch to master.

**Comment by shannona** [comment]
Let me take a look tonight, and I'll hand it back to you then.

**Comment by shannona** [comment]
I've changed toggle to option, per @hxw , should be ready to go.

**Comment by vienlt** [comment]
@shannona: Would you want to merge the branch to master or do you need my help?

**Comment by shannona** [comment]
Looks like I have the right permissions now, @vienlt, so I've merged.

**Pull request merged**
