### PR TITLE
Update payment documentation

### PR DESCRIPTION
**Pull request by lemonlatte**
Work on https://github.com/bitmark-inc/docs/issues/18

### CODE REVIEW

**Review by hxw — APPROVED** [review]

**Comment by vienlt** [comment]
@lemonlatte: Since @hxw already approved the PR, could you merge to master?

**Review by shannona — COMMENTED** [review]
This is nicely introduced and organized. My only suggestion here is that it should talk about how the "free" issuances that don't require a payment are managed: how that works as part of the process described here (even if it's just referencing another document).

**Comment by vienlt** [comment]
@lemonlatte: Could you check Shannon's comments?

**Comment by lemonlatte** [comment]
@shannona I previously thought that this section only contains transactions that need to pay by coins. Does your idea mean that it is better introduce the concept of **pay by hash**. It makes the scope of this section move into a bigger level.

**Comment by shannona** [comment]
> @shannona I previously thought that this section only contains transactions that need to pay by coins. Does your idea mean that it is better introduce the concept of **pay by hash**. It makes the scope of this section move into a bigger level.

That's an entirely reasonable division, but at a minimum I think you'd want to point to the other documentation (and let readers know that yes, there's another way to "pay" for some transactions).

**Comment by vienlt** [comment]
We merge the PR to master for the first deployment. Further updates can be done later.

**Pull request merged**
